# ========================
# SERVER
# ========================
server.port=8080

# ========================
# MYSQL / JPA
# ========================
spring.datasource.url=jdbc:mysql://localhost:3306/bookcorner_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ========================
# MONGODB
# ========================
spring.data.mongodb.uri=mongodb://localhost:27017/bookcorner_reviews

# ========================
# LOGGING
# ========================
logging.level.com.bookcorner=DEBUG
